//@ts-nocheck
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/kenney_conveyor_kit/robot-arm-b.glb --output src/components/Robotarm.tsx --transform 
Files: public/kenney_conveyor_kit/robot-arm-b.glb [44.57KB] > C:\Workspace\webdev\3D Task Factory\src\components\robot-arm-b-transformed.glb [5.16KB] (88%)
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['robot-arm-b_1']: THREE.Mesh
  }
  materials: {
    colormap: THREE.MeshStandardMaterial
  }
  animations: any[]
}

export function Robotarm(props: any) {
  const { nodes, materials } = useGLTF('/models/robot-arm-b-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['robot-arm-b_1'].geometry} material={materials.colormap} />
    </group>
  )
}

useGLTF.preload('/models/robot-arm-b-transformed.glb')
