//@ts-nocheck
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/kenney_conveyor_kit/arrow.glb --output src/scene/models/Arrow.tsx --transform 
Files: public/kenney_conveyor_kit/arrow.glb [3.86KB] > C:\Workspace\webdev\3D Task Factory\src\scene\models\arrow-transformed.glb [3.57KB] (8%)
*/

import * as THREE from 'three'
import { useRef, useState, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { motion } from 'framer-motion'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    arrow_1: THREE.Mesh
  }
  materials: {
    colormap: THREE.MeshStandardMaterial
  }
  animations: any[]
}

interface ArrowProps {
  position?: [number, number, number]
  rotation?: [number, number, number]
  onClick?: () => void
}

export function Arrow({ position = [0, 2, 0], rotation = [Math.PI / 2, Math.PI / 2, 0], onClick }: ArrowProps) {
  const { nodes, animations, materials } = useGLTF('/models/arrow-transformed.glb') as GLTFResult
  const groupRef = useRef(null)
  const [isHovered, setIsHovered] = useState(false)

  useEffect(() => {
    document.body.style.cursor = isHovered ? 'pointer' : 'auto'
    return () => {
      document.body.style.cursor = 'auto'
    }
  }, [isHovered])

  useFrame(() => {
    if (groupRef.current) {
      const targetScale = isHovered ? 1.2 : 1
      groupRef.current.scale.lerp(
        new THREE.Vector3(targetScale, targetScale, targetScale),
        0.1
      )
    }
  })

  return (
    <group
      ref={groupRef}
      position={position}
      rotation={rotation}
      onClick={onClick}
      onPointerEnter={() => setIsHovered(true)}
      onPointerLeave={() => setIsHovered(false)}
      dispose={null}
    >
      <mesh geometry={nodes.arrow_1.geometry} material={materials.colormap} />
    </group>
  )
}

useGLTF.preload('/models/arrow-transformed.glb')
