//@ts-nocheck
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/kenney_conveyor_kit/box-small.glb --output src/components/Box.tsx --transform 
Files: public/kenney_conveyor_kit/box-small.glb [4.04KB] > C:\Workspace\webdev\3D Task Factory\src\components\box-small-transformed.glb [3.55KB] (12%)
*/

import * as THREE from 'three'
import React, { useRef, useEffect, useState } from 'react'
import { useGLTF, Html } from '@react-three/drei'
import { motion } from 'framer-motion'
import type { GLTF } from 'three-stdlib'

export interface TaskData {
  id: string
  title: string
  description: string
  points: number
  status: 'todo' | 'in-progress' | 'done'
  position: [number, number, number]
}

interface TaskBoxProps extends TaskData {
  rotation?: [number, number, number]
  onClick?: (task: TaskData) => void
  isNew?: boolean
}

type GLTFResult = GLTF & {
  nodes: {
    ['box-small_1']: THREE.Mesh
  }
  materials: {
    colormap: THREE.MeshStandardMaterial
  }
  animations: any[]
}


export default function Box({
  id,
  title,
  description,
  points,
  status,
  position,
  rotation = [0, 0, 0],
  onClick,
  isNew = false,
}: TaskBoxProps) {
  const { nodes, materials } = useGLTF('/models/box-small-transformed.glb') as GLTFResult

  // Click handler
  const handlePointerDown = (e: any) => {
    e.stopPropagation()
    if (onClick) {
      onClick({ id, title, description, points, status, position })
    }
  }

  return (
    <motion.group
      position={position as any}
      rotation={rotation as any}
      initial={{ scale: isNew ? 0.5 : 1 }}
      animate={{ scale: 1 }}
      transition={{
        type: 'spring',
        stiffness: 100,
        damping: 15,
        duration: 0.6,
      }}
      dispose={null as any}
      onPointerDown={handlePointerDown}
      style={{ cursor: onClick ? 'pointer' : 'auto' } as any}
    >
      <mesh geometry={nodes['box-small_1'].geometry} material={materials.colormap} />
      {/* Floating UI with title and points */}
      <Html
        position={[0, 0.6, 0]}
        center
        style={{ pointerEvents: 'none', userSelect: 'none' }}
        distanceFactor={8}
      >
        <div style={{
          background: 'rgba(255,255,255,0.85)',
          borderRadius: 4,
          padding: '2px 8px',
          fontSize: 12,
          color: '#222',
          boxShadow: '0 1px 4px rgba(0,0,0,0.08)',
          minWidth: 40,
          textAlign: 'center',
          fontWeight: 500,
        }}>
          <div>{title || <span style={{ color: '#aaa' }}>No Title</span>}</div>
          <div style={{ fontSize: 10, color: '#888' }}>★ {points}</div>
        </div>
      </Html>
      <group userData={{ taskId: id, title, description, points, status }} />
    </motion.group>
  )
}

useGLTF.preload('/models/box-small-transformed.glb')
